In [1]:
import numpy as np


In [2]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
iris = fetch_ucirepo(id=53) 
  
# data (as pandas dataframes) 
X = iris.data.features 
y = iris.data.targets 
  
# metadata 
print(iris.metadata) 
  
# variable information 
print(iris.variables) 


{'uci_id': 53, 'name': 'Iris', 'repository_url': 'https://archive.ics.uci.edu/dataset/53/iris', 'data_url': 'https://archive.ics.uci.edu/static/public/53/data.csv', 'abstract': 'A small classic dataset from Fisher, 1936. One of the earliest known datasets used for evaluating classification methods.\n', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 150, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1936, 'last_updated': 'Tue Sep 12 2023', 'dataset_doi': '10.24432/C56C76', 'creators': ['R. A. Fisher'], 'intro_paper': {'title': 'The Iris data set: In search of the source of virginica', 'authors': 'A. Unwin, K. Kleinman', 'published_in': 'Significance, 2021', 'year': 2021, 'url': 'https://www.semanticscholar.org/paper/4599862ea877863669a6a8e63a3c707a787d5d7e', 'doi': '1740-9713.01589'}, 'add

In [3]:
X.head() 

sepal length  sepal width  petal length  petal width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [4]:
y.head()

class
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa

In [5]:
y = y.replace("Iris-setosa", 1)
y = y.replace("Iris-virginica", 2)
y=y.replace("Iris-versicolor", 3)


In [6]:
y.shape

(150, 1)

In [7]:
X.shape

(150, 4)

In [8]:
# import random

In [9]:
# random.shuffle(X)

# split_ratio= 0.8
# split_index = int(split_ratio*len(X))

# x_train_data = X[:split_index]
# x_test_data = X[split_index]
# y_train_data = y[:split_index]
# y_test_data = y[split_index]

def log_loss(y_true , y_pred):
    eplison = 1e-15
    y_pred_new =[max(i , eplison)for i in y_pred]
    y_pred_new = [min(i , 1-eplison)for i in y_pred_new]
    y_pred_new = np.array(y_pred_new)
    return -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))


In [47]:
class Shyam_NN:
    def __init__(self):
        self.w1 = 1
        self.w2 = 1
        self.w3 = 1
        self.w4 = 1
        self.bias =0
        self.eplison = 1e-15

    def fit(self,x , y , epochs ):
        self.w1 , self.w2 , self.w3 , self.w4 , self.bias = self.gradient_descent(x["sepal length"], x["sepal width"] , x["petal length"] ,x["petal width"] ,y["class"], epochs  = epochs)

    def predict(self , x):
        weigthed_sum = self.w1*x["sepal length"] + self.w2*x["sepal width"]+self.w3*x["petal length"]+ self.w4*x["petal width"]+ self.bias
        return self.sigmoid(weighted_sum)

    def sigmoid(self ,x):
        return 1/(1+np.exp(-x))

    def log_loss(self , y_true , y_pred):
        eplison = 1e-15
        y_pred_new =[max(i , eplison)for i in y_pred]
        y_pred_new = [min(i , 1-eplison)for i in y_pred_new]
        y_pred_new = np.array(y_pred_new)
        return -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))
        
    def gradient_descent(self,l1 , l2, l3 ,l4 , y_true , epochs):
        w1 =w2 = w3=w4=1
        bias = 0
        rate = 0.003
        n=  len(l1)
        for i in range(epochs):
            weighted_sum = w1*l1 +w2*l2 + w3*l3 +w4*l4+bias
            y_predicted =self.sigmoid(weighted_sum)
            loss= self.log_loss(y_true , y_predicted)
    
            w1d = (1/n)*np.dot(np.transpose(l1),(y_predicted - y_true))
            w2d = (1/n)*np.dot(np.transpose(l2), (y_predicted -y_true))
            w3d = (1/n)*np.dot(np.transpose(l3), (y_predicted -y_true))
            w4d = (1/n)*np.dot(np.transpose(l4), (y_predicted -y_true))
            print(w1d , w2d , w3d ,w4d )
            
            bias = np.mean(y_predicted-y_true)
    
            w1 = w1-rate*w1d
            w2 = w2-rate*w1d
            w3 = w3-rate*w1d
            w4 = w4-rate*w1d
            
    
            print(f'Epoch{i} w1:{w1} , w2:{w2} ,w3: {w3}, w4 :{w4}, bias={bias} , loss = {loss}')
        return w1 , w2 ,w3 ,w4 , bias


        

In [48]:
my_NN = Shyam_NN()
my_NN.fit(X,y, 1000)

Epoch0 w1:1.0184602643928744 , w2:1.0184602643928744 ,w3: 1.0184602643928744, w4 :1.0184602643928744, bias=-1.000018407444233 , loss = -15.241314925367345
Epoch1 w1:1.036920865343376 , w2:1.036920865343376 ,w3: 1.036920865343376, w4 :1.036920865343376, bias=-1.0000418835495632 , loss = -14.522632081186249
Epoch2 w1:1.055381368066389 , w2:1.055381368066389 ,w3: 1.055381368066389, w4 :1.055381368066389, bias=-1.0000350742400708 , loss = -14.803979587889769
Epoch3 w1:1.0738417887286151 , w2:1.0738417887286151 ,w3: 1.0738417887286151, w4 :1.0738417887286151, bias=-1.0000293791524304 , loss = -15.08535476887782
Epoch4 w1:1.0923021408262512 , w2:1.0923021408262512 ,w3: 1.0923021408262512, w4 :1.0923021408262512, bias=-1.0000246154124122 , loss = -15.366726652333512
Epoch5 w1:1.1107624356172467 , w2:1.1107624356172467 ,w3: 1.1107624356172467, w4 :1.1107624356172467, bias=-1.0000206295120697 , loss = -15.648095782697716
Epoch6 w1:1.1292226824959997 , w2:1.1292226824959997 ,w3: 1.12922268249599

In [46]:
coef

array([[5.957128 ],
       [5.9558125],
       [5.9610753],
       [5.9631543]], dtype=float32)

Model Using Tensorflow

In [12]:
import tensorflow as tf
from tensorflow import keras


In [39]:
model = keras.Sequential([keras.layers.Dense(1, input_shape=(4,), activation="sigmoid" ,kernel_initializer="ones" , bias_initializer="zeros" )])

In [40]:
model.compile(optimizer="adam",
             loss = "binary_crossentropy",
             metrics=["accuracy"])

In [41]:
model.fit(X , y , epochs=1000)

Epoch 1/1000
5/5 [==============================] - 0s 2ms/step - loss: -15.2710 - accuracy: 0.3333
Epoch 2/1000
5/5 [==============================] - 0s 2ms/step - loss: -15.3543 - accuracy: 0.3333
Epoch 3/1000
5/5 [==============================] - 0s 1ms/step - loss: -15.4338 - accuracy: 0.3333
Epoch 4/1000
5/5 [==============================] - 0s 2ms/step - loss: -15.5133 - accuracy: 0.3333
Epoch 5/1000
5/5 [==============================] - 0s 2ms/step - loss: -15.5941 - accuracy: 0.3333
Epoch 6/1000
5/5 [==============================] - 0s 1ms/step - loss: -15.6770 - accuracy: 0.3333
Epoch 7/1000
5/5 [==============================] - 0s 1ms/step - loss: -15.7548 - accuracy: 0.3333
Epoch 8/1000
5/5 [==============================] - 0s 2ms/step - loss: -15.8384 - accuracy: 0.3333
Epoch 9/1000
5/5 [==============================] - 0s 1ms/step - loss: -15.9140 - accuracy: 0.3333
Epoch 10/1000
5/5 [==============================] - 0s 2ms/step - loss: -15.9981 - accuracy: 0.3333

In [42]:
coef , intercept = model.get_weights()

In [43]:
coef

array([[5.957128 ],
       [5.9558125],
       [5.9610753],
       [5.9631543]], dtype=float32)

In [44]:
intercept

array([4.9544606], dtype=float32)