In [1]:
import numpy as np 
import pandas as pd

In [2]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
iris = fetch_ucirepo(id=53) 
  
# data (as pandas dataframes) 
X = iris.data.features 
y = iris.data.targets 
  
# metadata 
# print(iris.metadata) 
  
# variable information 
print(iris.variables) 


           name     role         type demographic  \
0  sepal length  Feature   Continuous        None   
1   sepal width  Feature   Continuous        None   
2  petal length  Feature   Continuous        None   
3   petal width  Feature   Continuous        None   
4         class   Target  Categorical        None   

                                         description units missing_values  
0                                               None    cm             no  
1                                               None    cm             no  
2                                               None    cm             no  
3                                               None    cm             no  
4  class of iris plant: Iris Setosa, Iris Versico...  None             no  


In [3]:
len(X)

150

In [4]:
data = pd.read_csv("data1.csv")

In [5]:
data.head()

area  bedrooms   price
0  1056         2   39.07
1  2600         4  120.00
2  1440         3   62.00
3  1521         3   75.00
4  1200         2   51.00

In [6]:
import random
random.shuffle(X["sepal length"])

split_ratio= 0.8
split_index = int(split_ratio*len(X))

x_train_data = X[:split_index]
x_test_data = X[split_index:]
y_train_data = y[:split_index]
y_test_data = y[split_index:]


C:\Users\r_ran\AppData\Local\Programs\Python\Python311\Lib\random.py:383: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[i], x[j] = x[j], x[i]


In [7]:
len(x_train_data)

120

In [8]:
len(x_test_data)

30

In [9]:
features = data.drop("price" , axis = 1)

In [10]:
target = data["price"]

### Batch Gradient Desecent

In [11]:
def batch_gradient_desecent(features , target , epochs , learning_rate = 0.03):
    num_features = features.shape[1]
    w = np.ones(shape =(num_features))
    bias = 0
    # print(num_features , w )
    total_sample = features.shape[0]
    # print(total_sample)

    cost_list = []
    epoch_list= []

    for i in range(epochs):
        y_pred = np.dot(w , features.T) + bias
        error = target - y_pred
        trans = np.transpose(features)
        # print(trans)
        w1 =  np.dot(trans , error)
        # print(w1)
        # print(error)
        # print(features.T.dot(target- y_pred))

        w_grad = (2/total_sample)*(features.T.dot(target -y_pred))
        b_grad = (2/total_sample)*np.sum(target - y_pred)


        w = w-learning_rate*w_grad
        bias = bias-learning_rate*b_grad


        cost = np.mean(np.square(target - y_pred))


        if i%10 ==0:
            cost_list.append(cost)
            epoch_list.append(i)


    return w , bias, cost , cost_list , epoch_list

In [12]:
w , bias ,cost ,cost_list , epoch  = batch_gradient_desecent(features , target , 20)

In [13]:
def predict(area , badroom , w ,bias):
    pred = w.iloc[0]*area + w.iloc[1]*badroom + bias
    return pred
    

In [14]:
y_pred = predict(1440,3,w,bias)

In [15]:
y_pred

6.366121749196729e+110

### Stochastic Gradient Descent 

In [16]:
def stochastic_gradient_descent(features , target , epochs , learning_rate = 0.03):
    number_of_features = features.shape[1]

    w1 = np.ones(shape = (number_of_features))
    b1 = 0
    total_sample = features.shape[0]

    cost_list = []
    epoch_list = []


    for i in range(epochs):
        random_index = random.randint(0 , total_sample-1)
        # print(random_index)
        sample_x = features.iloc[random_index]
        sample_y = target.iloc[random_index]
        sample_x = np.array(sample_x)
        sample_y = np.array(sample_y)
        y_predicted = np.dot(w , sample_x.T)+b1
        # print(y_predicted)
        # print(sample_y)
        # print(sample_x[1])
        # print(sample_x)
        w_grand = -(2/total_sample)*(sample_x.T.dot(sample_y - y_predicted))
        b_grand = -(2/total_sample)*(sample_y - y_predicted)


        w1 = w1-(learning_rate*w_grand)
        b1 = b1-(learning_rate*b_grand)


        cost = np.square(sample_y - y_predicted)


        if i%100==0:
            cost_list.append(cost)
            epoch_list.append(i)
    return w1 , b1 , cost , cost_list , epoch_list

In [17]:
w1 , b1 , cost1 , cost_list1 , epoch_list1 = stochastic_gradient_descent(features , target , 10000) 

In [18]:
features.iloc[12]

area        1000
bedrooms       2
Name: 12, dtype: int64

In [19]:
w1

array([-1.09742482e+115, -1.18426010e+112])

In [20]:
w

area        4.420903e+107
bedrooms    6.574672e+104
dtype: float64

### Mini Batch Gradient Descent my My Self

In [22]:
def mini_batch_gradient(features , target , epochs , learning_rate=0.03):
    number_of_features  = features.shape[1]
    w2 = np.ones(shape = (number_of_features))
    b2 = 0
    total_sample = features.shape[0]
    total = 10
    cost_list = []
    epoch_list = []

    for i in range(epochs):
        random_index = []
        for i in range(10):
            r_index = random.randint(0, total_sample-1)
            random_index.append(r_index)

        # print(random_index)
        sample_x = features.iloc[random_index]
        sample_y = target.iloc[random_index]
        sample_x = np.array(sample_x)
        sample_y = np.array(sample_y)
        # print(sample_x)
        # print(sample_y)
        y_pred = np.dot(w , sample_x.T)+b2
        
        w_grad = -(2/total)*(sample_x.T.dot(sample_y-y_pred))
        b_grad = -(2/total)*(sample_y-y_pred)
        
        w2 = w2-(learning_rate*w_grad)
        b2 =b2-(learning_rate*b_grad)

        cost = np.mean(np.square(sample_y - y_pred))

        if i%10 == 0:
            cost_list.append(cost)
            epoch_list.apped(i)
    return w2 , b2 , cost , cost_list, epoch_list

In [23]:
w2 , bias2 , cost , cost_list , epoch_list = mini_batch_gradient(features , target , 100)

In [24]:
w2

array([-8.82597814e+114, -1.28274055e+112])

In [25]:
bias2

array([-3.84484184e+110, -3.58709116e+110, -3.81547049e+110,
       -3.62034208e+110, -3.79007692e+110, -3.84422090e+110,
       -3.78350668e+110, -3.50167989e+110, -3.36185996e+110,
       -3.79079930e+110])

In [26]:
b1

-8.335897035928975e+110

### Mini Batch Gradicent Descent Internet

In [27]:
def mini_batch_G_D(features , target , epochs=10000 , batch_size = 5 , learning_rate = 0.03):
    number_of_features = features.shape[1]
    w3  = np.ones(shape=(number_of_features))
    b3 = 0
    total_sample = features.shape[0]

    if batch_size>total_sample:
        batch_size = total_sample

    cost_list = []
    epoch_list = []

    num_batches = int(total_sample/batch_size)

    for i  in range(epochs):
        random_indices = np.random.permutation(total_sample)
        x_tmp = features.iloc[random_indices]
        y_tmp = target.iloc[random_indices]


        for j in range(0 , total_sample , batch_size):
            Xj = x_tmp[j:j+batch_size]
            Yj = y_tmp[j:j+batch_size]
            y_pred = np.dot(w , Xj.T)+b3


            w_grad = -(2/len(Xj))*(Xj.T.dot(Yj-y_pred))
            b_grad = -(2/len(Yj))*np.sum(Yj-y_pred)


            w3= w3-learning_rate*w_grad
            b3 = b3-learning_rate*b_grad

            cost = np.mean(np.square(Yj- y_pred))


            if i%10==0:
                cost_list.append(cost)
                epoch_list.append(i)

            return w3 , b3 ,cost , cost_list , epoch_list

In [28]:
w3 , b3 , cost3 , cost_list , epoch_list = mini_batch_G_D(features , target)

In [29]:
w

area        4.420903e+107
bedrooms    6.574672e+104
dtype: float64

In [30]:
w1

array([-1.09742482e+115, -1.18426010e+112])

In [31]:
w3



area       -1.055334e+113
bedrooms   -1.653174e+110
dtype: float64

In [32]:
bias

1.999188131901224e+104

In [33]:
b1

-8.335897035928975e+110

In [34]:
b3

-4.565566569717403e+109